### ISSUE TITLE
@CreatedAt @LastModifiedAt @CreatedBy @LastModifiedBy not support in morphia

### ISSUE THREAD

**Issue by dreamingo88** [actframework/act-morphia#30]
@CreatedAt @LastModifiedAt @CreatedBy @LastModifiedBy not support in morphia

**Comment by dreamingo88** [comment]
it seams still not work with act-morphia 1.6.6+act 1.8.17

**Comment by greenlaw110** [comment]
@dreamingo88 I've added test case and proved it is working. Check out https://github.com/actframework/act-morphia/blob/master/testapps/ghissues/src/main/resources/test/scenarios/gh30.yml

**Comment by greenlaw110** [comment]
@dreamingo88 I've added test case and proved it is working. Check out https://github.com/actframework/act-morphia/blob/master/testapps/ghissues/src/main/resources/test/scenarios/gh30.yml
